'use client';
import { useEffect, useState } from 'react';
import LoadingScreen from '@/components/LoadingScreen';
import SelectMenu from '@/components/SelectMenu';
export default function AdminClient({email}:{email:string}){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);try{const r=await fetch('/api/admin',{cache:'no-store'});const d=await r.json();if(!r.ok){setError(d.error||'Access denied');return;}setData(d);setError('')}catch{setError('Unable to load admin workspace.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function update(payload:any){setBusy(true);try{const r=await fetch('/api/admin',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){alert(d.error||'Update failed');return;}await load()}finally{setBusy(false)}}
 if(error)return <section className="page"><div className="hero-card"><span className="eyebrow">403 · PRIVATE</span><h1>Admin access required</h1><p>{error}</p></div></section>;
 if(loading||!data)return <LoadingScreen label="Loading admin control center"/>;
 return <section className="page"><div className="page-heading"><div><span className="eyebrow">CONTROL CENTER</span><h1>Admin workspace</h1><p>Signed in as {email}. Manage users, plans and platform features.</p></div><span className="connection-pill is-on"><span/> Protected</span></div><div className="admin-grid"><div className="glass-card"><div className="card-title"><h2>Customers</h2><span>{data.users.length} accounts</span></div><div className="admin-list">{data.users.map((u:any)=><div className="admin-row" key={u.id}><div><strong>{u.email}</strong><small>{u.role} · {u.plan_name}</small></div><div className="admin-actions"><SelectMenu disabled={busy} value={u.plan_key} onChange={(value)=>void update({action:'set-plan',userId:u.id,planKey:value})} options={data.plans.map((p:any)=>({value:p.key,label:p.name}))} aria-label={`Plan for ${u.email}`} /><button className={busy?'loading-action':''} disabled={busy} onClick={()=>void update({action:'set-role',userId:u.id,role:u.role==='admin'?'user':'admin'})}>{busy?<span className="button-loading-skeleton" aria-hidden="true"/>:u.role==='admin'?'Remove admin':'Make admin'}</button></div></div>)}</div></div><div className="glass-card"><div className="card-title"><h2>Feature flags</h2><span>Platform controls</span></div><div className="admin-list">{data.features.map((f:any)=><div className="admin-row" key={f.id}><div><strong>{f.name}</strong><small>{f.description}</small></div><button type="button" className={`feature-toggle ${f.enabled ? 'is-enabled' : ''} ${busy ? 'is-busy' : ''}`} disabled={busy} onClick={()=>void update({action:'set-feature',featureId:f.id,enabled:!f.enabled})} aria-pressed={!!f.enabled} aria-label={`${f.enabled?'Disable':'Enable'} ${f.name}`}><span className="feature-toggle-track"><span className="feature-toggle-thumb"/></span><span className="feature-toggle-label">{busy ? '' : f.enabled ? 'On' : 'Off'}</span></button></div>)}</div></div></div></section>
}
