import { NextRequest, NextResponse } from 'next/server';
import { getSession } from '@/lib/session';
import { query } from '@/lib/db';
import { upsertUser } from '@/lib/app-user';
export const runtime='nodejs';
export async function GET(){const s=await getSession();if(!s)return NextResponse.json({error:'Connect Gmail first.'},{status:401});const u=await upsertUser(s.email);const {rows}=await query(`SELECT id,name,subject,body,created_at,updated_at FROM templates WHERE user_id=$1 ORDER BY updated_at DESC`,[u.id]);return NextResponse.json({templates:rows});}
export async function POST(req:NextRequest){const s=await getSession();if(!s)return NextResponse.json({error:'Connect Gmail first.'},{status:401});const b=await req.json();if(!b.name||!b.subject||!b.body)return NextResponse.json({error:'Name, subject and body are required.'},{status:400});const u=await upsertUser(s.email);const {rows}=await query(`INSERT INTO templates(user_id,name,subject,body) VALUES($1,$2,$3,$4) RETURNING *`,[u.id,b.name,b.subject,b.body]);return NextResponse.json({template:rows[0]});}
export async function PATCH(req:NextRequest){const s=await getSession();if(!s)return NextResponse.json({error:'Connect Gmail first.'},{status:401});const b=await req.json();if(!b.id||!b.name||!b.subject||!b.body)return NextResponse.json({error:'Template name, subject and body are required.'},{status:400});const u=await upsertUser(s.email);const {rows}=await query(`UPDATE templates SET name=$1,subject=$2,body=$3,updated_at=now() WHERE id=$4 AND user_id=$5 RETURNING *`,[b.name,b.subject,b.body,b.id,u.id]);if(!rows[0])return NextResponse.json({error:'Template not found.'},{status:404});return NextResponse.json({template:rows[0]});}
export async function DELETE(req:NextRequest){const s=await getSession();if(!s)return NextResponse.json({error:'Connect Gmail first.'},{status:401});const id=new URL(req.url).searchParams.get('id');if(!id)return NextResponse.json({error:'Template id is required.'},{status:400});const u=await upsertUser(s.email);const {rowCount}=await query(`DELETE FROM templates WHERE id=$1 AND user_id=$2`,[id,u.id]);if(!rowCount)return NextResponse.json({error:'Template not found.'},{status:404});return NextResponse.json({ok:true});}
