'use client';
import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import LoadingScreen from '@/components/LoadingScreen';
import LoginRequired from '@/components/LoginRequired';
import { getAuthStatus } from '@/lib/client-auth';
import SelectMenu from '@/components/SelectMenu';

type Contact={id:string;email:string;name?:string;total_sent:number;total_failed:number;last_contacted_at?:string;last_subject?:string;last_status?:string};
type Pagination={page:number;pages:number;total:number};

export default function Contacts(){
 const [auth,setAuth]=useState<'loading'|'guest'|'ready'>('loading'); const [items,setItems]=useState<Contact[]>([]); const [loading,setLoading]=useState(true); const [q,setQ]=useState(''); const [submittedQuery,setSubmittedQuery]=useState(''); const [error,setError]=useState(''); const [activityFilter,setActivityFilter]=useState('all'); const [page,setPage]=useState(1); const [pagination,setPagination]=useState<Pagination>({page:1,pages:1,total:0});
 const load=useCallback(async()=>{setLoading(true);setError('');try{const params=new URLSearchParams({q:submittedQuery,page:String(page),limit:'50'});const r=await fetch(`/api/contacts?${params}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load contacts');setItems(d.contacts||[]);setPagination(d.pagination||{page:1,pages:1,total:0})}catch(e:any){setError(e.message||'Could not load contacts')}finally{setLoading(false)}},[page,submittedQuery]);
 useEffect(()=>{let live=true;getAuthStatus().then(d=>{if(!live)return;if(!d.connected){setAuth('guest');setLoading(false);return}setAuth('ready')}).catch(()=>{if(live){setAuth('guest');setLoading(false)}});return()=>{live=false}},[]);
 useEffect(()=>{if(auth==='ready')void load()},[auth,load]);
 const filteredItems=useMemo(()=>items.filter(x=>activityFilter==='all'||(activityFilter==='failed'&&x.total_failed>0)||(activityFilter==='active'&&x.total_sent>0&&x.total_failed===0)),[items,activityFilter]);
 const stats=useMemo(()=>({sent:items.reduce((n,x)=>n+x.total_sent,0),failed:items.reduce((n,x)=>n+x.total_failed,0)}),[items]);
 const submitSearch=()=>{setPage(1);setSubmittedQuery(q.trim())};
 if(auth==='loading')return <LoadingScreen label="Loading contacts"/>; if(auth==='guest')return <LoginRequired title="Your contacts are private" description="Connect Gmail to see everyone you've emailed and their complete message history."/>;
 return <>
  <div className="floating-page-head campaigns-head"><div><div className="eyebrow">CONTACTS</div><h1>Everyone you’ve emailed.</h1><p>A growing contact history built automatically from your campaigns. Open a contact to see every message and delivery result.</p></div><Link href="/dashboard" className="btn btn-primary">New campaign <span>→</span></Link></div>
  <section className="campaign-overview"><div className="campaign-overview-card"><span>Contacts</span><strong>{loading?'—':pagination.total.toLocaleString()}</strong><small>People in your workspace</small></div><div className="campaign-overview-card"><span>Page sends</span><strong className="success-text">{loading?'—':stats.sent.toLocaleString()}</strong><small>Across this page</small></div><div className="campaign-overview-card"><span>Page failures</span><strong className={stats.failed?'danger-text':''}>{loading?'—':stats.failed.toLocaleString()}</strong><small>Needs attention</small></div></section>
  <section className="campaigns-panel float-panel"><div className="campaigns-toolbar"><div><h2>Contact history</h2><p>{loading?'Loading contacts…':`${filteredItems.length} of ${pagination.total.toLocaleString()} contacts`}</p></div><div className="filter-row"><label className="search-wrap"><span aria-hidden="true">⌕</span><input aria-label="Search contacts" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submitSearch()} placeholder="Search name or email"/></label><SelectMenu className="filter-select" value={activityFilter} onChange={setActivityFilter} options={[{value:'all',label:'All contacts'},{value:'active',label:'Successful only'},{value:'failed',label:'Needs attention'}]} aria-label="Contact filter"/></div></div>
   {error?<div className="floating-alert" role="alert">{error}<button className="alert-action" onClick={load}>Try again</button></div>:loading?<div className="table-skeleton-wrap" role="status" aria-label="Loading contacts"><div className="table-skeleton-head">{Array.from({length:5}).map((_,i)=><span key={i}/>)}</div>{Array.from({length:6}).map((_,r)=><div className="table-skeleton-row" key={r}>{Array.from({length:5}).map((_,i)=><span key={i}/>)}</div>)}</div>:!items.length?<div className="empty-state campaign-empty"><div className="empty-icon">◎</div><h2>No contacts yet</h2><p>Once you send a campaign, recipients will automatically appear here.</p></div>:<><div className="campaign-table contacts-table"><div className="campaign-row campaign-header"><span>Contact</span><span>Sent</span><span>Failed</span><span>Last message</span><span>Last contacted</span></div>{filteredItems.map(x=><Link href={`/contacts/${x.id}`} className="campaign-row campaign-row-link" key={x.id}><span className="campaign-main"><b>{x.name||x.email}</b><small>{x.email}</small></span><span><b className="success-text">{x.total_sent}</b></span><span><b className={x.total_failed?'danger-text':''}>{x.total_failed}</b></span><span><b>{x.last_subject||'—'}</b><small>{x.last_status||'—'}</small></span><span><b>{x.last_contacted_at?new Date(x.last_contacted_at).toLocaleDateString():'—'}</b><small>{x.last_contacted_at?new Date(x.last_contacted_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):''}</small></span></Link>)}</div>{pagination.pages>1&&<div className="table-pagination"><span>Page {pagination.page} of {pagination.pages}</span><div><button className="ghost-btn small" disabled={pagination.page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="ghost-btn small" disabled={pagination.page===pagination.pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>}</>}
  </section>
 </>;
}
