'use client';
import { useEffect, useMemo, useState } from 'react';
import ConnectCard from '@/components/ConnectCard';
import { getAuthStatus } from '@/lib/client-auth';
import SelectMenu from '@/components/SelectMenu';

type Recipient={email:string;name?:string;row?:number;source:'excel'|'paste';data?:Record<string,string>;verified?:boolean;verifyReason?:string};
type Attachment={filename:string;contentType:string;data:string;size:number};
const emailRe=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function normalizeEmail(v:unknown){return String(v??'').trim().toLowerCase()}
function escapeHtml(v:string){return v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function extractEmails(text:string){const found:string[]=[];const seen=new Set<string>();for(const token of text.split(/[\s,;]+/)){const m=token.trim().match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);if(m){const email=normalizeEmail(m[0]);if(!seen.has(email)){seen.add(email);found.push(email)}}}return found}

export default function Dashboard(){
 const [connected,setConnected]=useState(false),[account,setAccount]=useState(''),[plan,setPlan]=useState<any>(null),[authLoading,setAuthLoading]=useState(true);
 const [recipients,setRecipients]=useState<Recipient[]>([]),[selected,setSelected]=useState<Set<string>>(new Set());
 const [fileName,setFileName]=useState(''),[paste,setPaste]=useState(''),[search,setSearch]=useState(''),[recipientFilter,setRecipientFilter]=useState('all'),[recipientLimit,setRecipientLimit]=useState(50);
 const [mapping,setMapping]=useState<{headers:string[];rows:any[][]}|null>(null),[mappingOpen,setMappingOpen]=useState(false),[emailField,setEmailField]=useState(''),[nameField,setNameField]=useState('');
 const [templates,setTemplates]=useState<any[]>([]),[templateId,setTemplateId]=useState('');
 const [subject,setSubject]=useState(''),[body,setBody]=useState(''),[scheduleAt,setScheduleAt]=useState('');
 const [attachment,setAttachment]=useState<Attachment|null>(null),[logs,setLogs]=useState<string[]>([]);
 const [sending,setSending]=useState(false),[done,setDone]=useState(0),[error,setError]=useState('');
 const [verifyState,setVerifyState]=useState<'idle'|'checking'|'done'>('idle'),[verifySummary,setVerifySummary]=useState('');

 const valid=useMemo(()=>recipients.filter(r=>emailRe.test(r.email)),[recipients]);
 const filtered=useMemo(()=>valid.filter(r=>{const q=search.trim().toLowerCase();const matchesSearch=!q||r.email.includes(q)||(r.name||'').toLowerCase().includes(q);const matchesStatus=recipientFilter==='all'||(recipientFilter==='verified'&&r.verified===true)||(recipientFilter==='attention'&&r.verified===false)||(recipientFilter==='unchecked'&&r.verified!==true&&r.verified!==false);return matchesSearch&&matchesStatus}),[valid,search,recipientFilter]);
 const selectedRecipients=useMemo(()=>valid.filter(r=>selected.has(r.email)),[valid,selected]);
 const previewRecipient=selectedRecipients[0];

 async function refreshStatus(force=false){try{const d=await getAuthStatus(force);setConnected(!!d.connected);setAccount(d.email||'');setPlan(d.plan||null);if(d.connected){fetch('/api/templates',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(v=>setTemplates(v?.templates||[])).catch(()=>{})}}catch{setConnected(false)}finally{setAuthLoading(false)}}
 useEffect(()=>{const params=new URLSearchParams(window.location.search);const justConnected=params.has('connected');refreshStatus(justConnected);const e=params.get('error');if(e)setError(e==='oauth_failed'?'Google authorization failed. Check your OAuth settings.':e==='no_refresh_token'?'Google did not return a refresh token. Reconnect Gmail from your Google account.':e==='oauth_state'?'OAuth session expired. Start Connect Gmail again.':'Google connection could not be completed.');if(params.has('connected'))window.history.replaceState({},'',window.location.pathname)},[]);

 function mergeRecipients(next:Recipient[],message:string){setRecipients(prev=>{const map=new Map(prev.map(r=>[r.email,r]));for(const r of next){if(!map.has(r.email))map.set(r.email,r)}return [...map.values()]});setSelected(prev=>{const n=new Set(prev);next.forEach(r=>n.add(r.email));return n});setLogs(prev=>[...prev,message])}
 async function loadExcel(e:React.ChangeEvent<HTMLInputElement>){setError('');const f=e.target.files?.[0];if(!f)return;setFileName(f.name);try{const XLSX=await import('xlsx');const wb=XLSX.read(await f.arrayBuffer());const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<any[]>(ws,{header:1,defval:''});if(!rows.length)throw new Error('Spreadsheet is empty.');const headers=rows[0].map((x:any)=>String(x).trim()).filter(Boolean);if(!headers.length)throw new Error('The first row must contain column names.');const lower=headers.map(h=>h.toLowerCase());const email=headers.find((h,i)=>['email','email address','e-mail'].includes(lower[i]))||headers[0];const name=headers.find((h,i)=>['name','full name','recipient name','first name'].includes(lower[i]))||'';setMapping({headers,rows:rows.slice(1)});setEmailField(email);setNameField(name);setMappingOpen(true);setVerifyState('idle');setVerifySummary('')}catch(err:any){setError(err.message||'Could not read spreadsheet.')}}
 function applyMapping(){if(!mapping)return;const ei=mapping.headers.indexOf(emailField),ni=nameField?mapping.headers.indexOf(nameField):-1;const incoming=new Set<string>();const out:Recipient[]=[];mapping.rows.forEach((row,i)=>{const email=normalizeEmail(row[ei]);if(email&&emailRe.test(email)&&!incoming.has(email)){incoming.add(email);const data:Record<string,string>={};mapping.headers.forEach((h,j)=>data[h]=String(row[j]??'').trim());out.push({email,name:ni>=0?String(row[ni]??'').trim():undefined,row:i+2,source:'excel',data})}});if(!out.length){setError('No valid emails found in the selected email column.');return}mergeRecipients(out,`Loaded ${out.length} unique recipients from ${fileName}`);setMappingOpen(false)}
 function addPasted(){setError('');const emails=extractEmails(paste);if(!emails.length){setError('No valid email addresses found.');return}const fresh=emails.map(email=>({email,source:'paste' as const}));mergeRecipients(fresh,`Added ${fresh.filter(r=>!recipients.some(x=>x.email===r.email)).length} new recipients`);setPaste('');setVerifyState('idle');setVerifySummary('')}
 function clearAll(){setRecipients([]);setSelected(new Set());setFileName('');setPaste('');setMapping(null);setVerifyState('idle');setVerifySummary('');setLogs([]);setDone(0)}
 function personalize(text:string,r?:Recipient){return text.replace(/\{\{([^}]+)\}\}/g,(_,raw)=>{const key=String(raw).trim();if(key.toLowerCase()==='name')return escapeHtml(r?.name||r?.email?.split('@')[0]||'Alex');if(key.toLowerCase()==='email')return escapeHtml(r?.email||account||'alex@example.com');const match=Object.keys(r?.data||{}).find(k=>k.toLowerCase()===key.toLowerCase());return match?escapeHtml(r!.data![match]):`{{${key}}}`})}
 function useTemplate(id:string){setTemplateId(id);const t=templates.find(x=>x.id===id);if(t){setSubject(t.subject||'');setBody(t.body||'')}}
 async function verifyRecipients(){if(!selectedRecipients.length){setError('Select recipients first.');return false}setVerifyState('checking');setError('');try{const r=await fetch('/api/verify-emails',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({emails:selectedRecipients.map(x=>x.email)})});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'Could not verify recipients.');const map=new Map<string,{valid:boolean;reason?:string}>((d.results||[]).map((x:any)=>[x.email,x]));const bad=selectedRecipients.filter(x=>!map.get(x.email)?.valid);setRecipients(prev=>prev.map(x=>map.has(x.email)?{...x,verified:!!map.get(x.email)?.valid,verifyReason:map.get(x.email)?.reason}:x));setVerifyState('done');setVerifySummary(bad.length?`${bad.length} recipient${bad.length===1?'':'s'} need attention.`:`All ${selectedRecipients.length} selected recipients are ready.`);if(bad.length){setError(bad.slice(0,5).map(x=>`${x.email}: ${map.get(x.email)?.reason||'Could not verify'}`).join(' · '));return false}return true}catch(e:any){setVerifyState('idle');setError(e.message||'Could not verify recipients.');return false}}
 async function loadAttachment(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(f.size>4*1024*1024){setError('Attachment limit is 4 MB.');return}const b=await f.arrayBuffer();let binary='';const bytes=new Uint8Array(b);for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));setAttachment({filename:f.name,contentType:f.type||'application/octet-stream',data:btoa(binary),size:f.size})}
 async function send(){setError('');if(!connected)return setError('Connect Gmail first.');if(!selectedRecipients.length)return setError('Select at least one recipient.');if(!subject.trim()||!body.trim())return setError('Subject and email body are required.');if(verifyState!=='done'){const ok=await verifyRecipients();if(!ok)return}if(!selectedRecipients.every(r=>r.verified===true))return setError('Please verify all selected recipients before sending.');if(!confirm(`You are about to send ${selectedRecipients.length} emails. Continue?`))return;setSending(true);setDone(0);setLogs([]);let campaignId='';let success=0;try{const cr=await fetch('/api/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,body,sourceName:fileName,attachmentName:attachment?.filename,scheduledAt:scheduleAt||null,recipients:selectedRecipients})});const cd=await cr.json();if(!cr.ok)throw new Error(cd.error||'Could not create campaign');campaignId=cd.campaignId;if(scheduleAt){setLogs([`✓ Campaign scheduled for ${new Date(scheduleAt).toLocaleString()}`]);setSending(false);return}for(let i=0;i<selectedRecipients.length;i++){const r=selectedRecipients[i];setLogs(v=>[...v,`Sending ${i+1}/${selectedRecipients.length} → ${r.email}`]);try{const res=await fetch('/api/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to:r.email,subject:personalize(subject,r),html:personalize(body,r).replace(/\n/g,'<br>'),attachment,campaignId})});const d=await res.json();if(!res.ok)throw new Error(d.error||'Failed');success++;setDone(i+1);setLogs(v=>[...v,`✓ Sent ${i+1}/${selectedRecipients.length} → ${r.email}`])}catch(err:any){setLogs(v=>[...v,`✗ Failed → ${r.email}: ${err.message||'Unknown error'}`])}}if(campaignId)await fetch(`/api/campaigns/${campaignId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:success===selectedRecipients.length?'completed':'completed_with_errors',failed:selectedRecipients.length-success})});await refreshStatus();setLogs(v=>[...v,`Finished — ${success} sent, ${selectedRecipients.length-success} failed.`])}catch(e:any){setError(e.message||'Could not send campaign.')}finally{setSending(false)}}
 async function saveDraft(){setError('');if(!selectedRecipients.length)return setError('Select at least one recipient.');try{const r=await fetch('/api/campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'draft',subject,body,sourceName:fileName,attachmentName:attachment?.filename,recipients:selectedRecipients})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save draft');setLogs(v=>[...v,`✓ Draft saved · ${d.campaignId}`])}catch(e:any){setError(e.message||'Could not save draft')}}
 async function saveList(){const name=window.prompt('Name this recipient list');if(!name)return;try{const r=await fetch('/api/recipient-lists',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,recipients:selectedRecipients})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save list');setLogs(v=>[...v,`✓ Saved recipient list “${name}”`])}catch(e:any){setError(e.message||'Could not save list')}}

 return <>
  <div className="dash-head-v4">
    <div>
      <div className="dash-eyebrow-v4"><span className="dash-eyebrow-dot"/> CAMPAIGN CONTROL CENTER</div>
      <h1>Ship better campaigns, <em>faster.</em></h1>
      <p>Import your audience, personalize every message, verify recipients, and send through Gmail from one focused workspace.</p>
    </div>
    <div className="dash-head-actions-v4">
      <div className={`dash-connect-v4 ${connected?'on':''}`}><span/>{connected ? `Gmail · ${account}` : 'Gmail not connected'}</div>
      <div className="dash-plan-v4"><b>{plan?.name||'Free'}</b><span>{Number(plan?.remainingThisMonth??plan?.monthlySendLimit??100).toLocaleString()} sends left</span></div>
    </div>
  </div>

  {error&&<div className="dash-alert-v4">{error}</div>}
  {!connected&&<ConnectCard/>}

  <section className="dash-kpis-v4">
    <div className="dash-kpi-v4 kpi-purple"><div className="kpi-icon">◎</div><span>Audience</span><strong>{valid.length.toLocaleString()}</strong><small>{fileName||'No source loaded'}</small><div className="kpi-glow"/></div>
    <div className="dash-kpi-v4 kpi-blue"><div className="kpi-icon">✓</div><span>Selected</span><strong>{selectedRecipients.length.toLocaleString()}</strong><small>{valid.length?`${Math.round(selectedRecipients.length/valid.length*100)}% of audience`:'Select recipients'}</small><div className="kpi-glow"/></div>
    <div className="dash-kpi-v4 kpi-orange"><div className="kpi-icon">↗</div><span>Monthly sends</span><strong>{Number(plan?.remainingThisMonth??plan?.monthlySendLimit??100).toLocaleString()}</strong><small>{plan?.name||'Free'} plan remaining</small><div className="kpi-glow"/></div>
    <div className="dash-kpi-v4 kpi-green"><div className="kpi-icon">●</div><span>This run</span><strong>{done.toLocaleString()}</strong><small>{sending?'Sending now':'Ready when you are'}</small><div className="kpi-glow"/></div>
  </section>

  <section className="dash-overview-v4">
    <div className="dash-section-title-v4"><div><span className="dash-number-v4 purple">01</span><div><div className="dash-kicker-v4">AUDIENCE</div><h2>Bring your data</h2></div></div><button className="dash-quiet-btn-v4" onClick={clearAll} disabled={!valid.length}>Clear workspace</button></div>
    <div className="dash-source-v4">
      <label className="dash-upload-v4"><input className="visually-hidden" type="file" accept=".xlsx,.xls,.csv" onChange={loadExcel}/><div className="dash-upload-icon">↑</div><strong>Drop your CSV or Excel file</strong><span>Upload a spreadsheet and map fields in seconds</span><b>Choose file</b></label>
      <div className="dash-paste-v4"><div className="dash-card-label-v4"><strong>Paste addresses</strong><span>comma · space · semicolon · newline</span></div><textarea value={paste} onChange={e=>setPaste(e.target.value)} placeholder="name@example.com\nteam@example.com"/><button className="dash-secondary-v4" onClick={addPasted} disabled={!paste.trim()}>Add recipients</button></div>
    </div>
    {valid.length>0&&<div className="dash-recipient-area-v4"><div className="dash-list-head-v4"><div><strong>{selectedRecipients.length} selected</strong><span> · {valid.length} loaded</span></div><div className="dash-list-tools-v4"><label className="dash-search-v4">⌕<input aria-label="Search recipients" value={search} onChange={e=>{setSearch(e.target.value);setRecipientLimit(50)}} placeholder="Search recipients"/></label><SelectMenu value={recipientFilter} onChange={value=>{setRecipientFilter(value);setRecipientLimit(50)}} options={[{value:'all',label:'All'},{value:'verified',label:'Verified'},{value:'attention',label:'Needs attention'},{value:'unchecked',label:'Not checked'}]} aria-label="Recipient filter" /><button onClick={()=>setSelected(new Set(filtered.map(r=>r.email)))}>Select all filtered</button><button onClick={saveList}>Save list</button></div></div><div className="dash-recipient-list-v4"><div className="dash-rec-row-v4 head"><span></span><span>Recipient</span><span>Source</span><span>Status</span></div>{filtered.slice(0,recipientLimit).map(r=><label className="dash-rec-row-v4" key={r.email}><input type="checkbox" checked={selected.has(r.email)} onChange={()=>setSelected(prev=>{const n=new Set(prev);n.has(r.email)?n.delete(r.email):n.add(r.email);return n})}/><span><strong>{r.name||r.email}</strong><small>{r.email}</small></span><span>{r.source}</span><span className={r.verified===false?'danger-text':r.verified===true?'success-text':''}>{r.verified===true?'Verified':r.verified===false?'Needs attention':'Not checked'}</span></label>)}</div>{filtered.length>recipientLimit&&<button type="button" className="dash-more-v4" onClick={()=>setRecipientLimit(v=>v+50)}>Show 50 more recipients ({filtered.length-recipientLimit} remaining)</button>}</div>}
  </section>

  <section className="dash-builder-grid-v4">
    <div className="dash-compose-v4">
      <div className="dash-section-title-v4"><div><span className="dash-number-v4 blue">02</span><div><div className="dash-kicker-v4">MESSAGE</div><h2>Build the message</h2></div></div></div>
      <p className="dash-section-copy-v4">Write once and let your spreadsheet fields make every email feel personal.</p>
      <div className="dash-compose-top-v4"><label>Saved template<SelectMenu value={templateId} onChange={useTemplate} options={[{value:'',label:'Start from scratch'},...templates.map(t=>({value:t.id,label:t.name}))]} aria-label="Saved template" /></label>{mapping&&<button className="dash-quiet-btn-v4" type="button" onClick={()=>setMappingOpen(true)}>Edit mapping</button>}</div>
      <label className="dash-field-v4">Subject<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Your subject line"/></label>
      <div className="dash-token-row-v4"><span>Insert field</span><button onClick={()=>setBody(v=>v+' {{name}}')}>Name</button><button onClick={()=>setBody(v=>v+' {{email}}')}>Email</button>{mapping?.headers.slice(0,4).filter(h=>h!==emailField&&h!==nameField).map(h=><button key={h} onClick={()=>setBody(v=>v+` {{${h}}}`)}>{h}</button>)}</div>
      <label className="dash-field-v4">Message<textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a clear, human email..."/></label>
      <label className="dash-attachment-v4"><input className="visually-hidden" type="file" onChange={loadAttachment}/><span className="attachment-icon">+</span><span><strong>{attachment?.filename||'Attach a file'}</strong><small>{attachment?`${(attachment.size/1024/1024).toFixed(2)} MB · ready`:'Up to 4 MB'}</small></span></label>
      {attachment&&<button className="dash-remove-v4" onClick={()=>setAttachment(null)}>Remove attachment</button>}
      <div className="dash-schedule-v4"><label className="dash-field-v4">Schedule (optional)<input type="datetime-local" value={scheduleAt} onChange={e=>setScheduleAt(e.target.value)}/></label><button className="dash-secondary-v4" onClick={saveDraft} disabled={sending}>Save draft</button></div>
    </div>

    <aside className="dash-preview-v4">
      <div className="dash-preview-top-v4"><div><div className="dash-kicker-v4">LIVE PREVIEW</div><h3>How it will look</h3></div><span className="preview-live-dot">LIVE</span></div>
      <div className="dash-preview-recipient-v4">{previewRecipient?<><span className="preview-avatar">{(previewRecipient.name||previewRecipient.email).slice(0,1).toUpperCase()}</span><div><strong>{previewRecipient.name||previewRecipient.email}</strong><small>{previewRecipient.email}</small></div></>:<span>Select a recipient to preview personalization</span>}</div>
      <div className="dash-email-v4"><div className="email-from-v4"><span className="mail-avatar">B</span><div><strong>Bulkmailer</strong><small>{account||'hello@bulkmailer'}</small></div></div><div className="email-subject-v4">{personalize(subject||'Your subject line',previewRecipient)}</div><div className="email-body-v4">{personalize(body||'Your message will appear here. Add {{name}} or other spreadsheet fields to see personalization live.',previewRecipient)}</div><div className="email-line-v4"/><small className="email-meta-v4">Sent through Gmail · personalized for this recipient</small></div>
      <div className="dash-preview-tip-v4"><span>✦</span><p><strong>Personalization is live.</strong> Tokens such as {'{{name}}'} and {'{{email}}'} are replaced for each recipient.</p></div>
    </aside>
  </section>

  <section className="dash-review-v4">
    <div className="dash-review-title-v4"><div><span className="dash-number-v4 orange">03</span><div><div className="dash-kicker-v4">REVIEW & SEND</div><h2>Final checks before launch</h2></div></div><span className={`dash-ready-pill-v4 ${verifyState==='done'?'ready':''}`}>{verifyState==='done'?'READY TO SEND':'PRE-FLIGHT'}</span></div>
    <div className="dash-checks-v4"><div className={selectedRecipients.length?'ok':''}><span>✓</span><div><strong>Audience</strong><small>{selectedRecipients.length?`${selectedRecipients.length} recipients selected`:'Select recipients'}</small></div></div><div className={verifyState==='done'?'ok':''}><span>✓</span><div><strong>Verification</strong><small>{verifySummary||'Verify recipients before sending'}</small></div></div><div className={subject.trim()&&body.trim()?'ok':''}><span>✓</span><div><strong>Message</strong><small>{subject.trim()&&body.trim()?'Subject and body are ready':'Add subject and message'}</small></div></div><div className={connected?'ok':''}><span>✓</span><div><strong>Gmail</strong><small>{connected?'Connected and ready':'Connect Gmail'}</small></div></div></div>
    <div className="dash-review-actions-v4"><button className="dash-secondary-v4" onClick={verifyRecipients} disabled={sending||verifyState==='checking'}>{verifyState==='checking'?'Checking…':'Verify recipients'}</button><button className="dash-send-v4" onClick={send} disabled={sending||!selectedRecipients.length}>{sending?`Sending ${done}/${selectedRecipients.length}`:scheduleAt?'Schedule campaign →':'Review & send →'}</button></div>
  </section>

  <section className="dash-activity-v4"><div className="dash-activity-title-v4"><div><span className="dash-number-v4 green">04</span><div><div className="dash-kicker-v4">ACTIVITY</div><h2>Recipient activity</h2></div></div><span className={sending?'live':'ready'}>{sending?'● LIVE':'READY'}</span></div><div className="dash-log-v4">{logs.length?logs.map((l,i)=><div key={i}><span className="log-dot"/>{l}</div>):<span>No activity yet. Verify your audience or send a campaign to see events here.</span>}</div></section>

  {mappingOpen&&<div className="modal-backdrop" role="dialog" aria-modal="true"><div className="mapping-modal float-panel"><div className="float-panel-head"><div><div className="eyebrow">CSV FIELD MAPPING</div><h2>Map your spreadsheet</h2><p>Choose the email and name columns. Every other column remains available for personalization.</p></div><button className="ghost-btn" onClick={()=>setMappingOpen(false)}>Close</button></div><div className="mapping-grid"><label className="field-label">Email column<SelectMenu value={emailField} onChange={setEmailField} options={(mapping?.headers||[]).map(h=>({value:h,label:h}))} aria-label="Email column" /></label><label className="field-label">Name column<SelectMenu value={nameField} onChange={setNameField} options={[{value:'',label:'No name column'},...(mapping?.headers||[]).map(h=>({value:h,label:h}))]} aria-label="Name column" /></label></div><div className="mapping-fields">{mapping?.headers.map(h=><span key={h}><b>{h}</b><small>{h===emailField?'Email':h===nameField?'Name':'Personalization'}</small></span>)}</div><div className="modal-actions"><button className="ghost-btn" onClick={()=>setMappingOpen(false)}>Cancel</button><button className="btn btn-primary" onClick={applyMapping}>Apply mapping</button></div></div></div>}
 </>;
}
