'use client';
import {useEffect,useState} from 'react';
import LoginRequired from '@/components/LoginRequired';
import LoadingScreen from '@/components/LoadingScreen';
import { getAuthStatus } from '@/lib/client-auth';
import { Copy, Pencil, Search, Trash2 } from 'lucide-react';

export default function Templates(){
 const [auth,setAuth]=useState<'loading'|'guest'|'ready'>('loading');const [templates,setTemplates]=useState<any[]>([]);const [query,setQuery]=useState('');const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [form,setForm]=useState({name:'',subject:'',body:''});const [editingId,setEditingId]=useState('');const [error,setError]=useState('');
 async function boot(){try{const sd=await getAuthStatus();if(!sd.connected){setAuth('guest');return}setAuth('ready');setLoading(true);const r=await fetch('/api/templates',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not load templates');setTemplates(d.templates||[])}catch(e:any){setError(e.message||'Could not load templates')}finally{setLoading(false)}}useEffect(()=>{boot()},[]);
 function cancel(){setEditingId('');setForm({name:'',subject:'',body:''})}function edit(t:any){setEditingId(t.id);setForm({name:t.name||'',subject:t.subject||'',body:t.body||''});window.scrollTo({top:0,behavior:'smooth'})}
 async function save(){setError('');if(!form.name||!form.subject||!form.body){setError('Complete all template fields.');return}setSaving(true);try{const r=await fetch('/api/templates',{method:editingId?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(editingId?{...form,id:editingId}:form)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Could not save');setTemplates(v=>editingId?v.map(t=>t.id===editingId?d.template:t):[d.template,...v]);cancel()}catch(e:any){setError(e.message||'Could not save')}finally{setSaving(false)}}
 async function remove(t:any){if(!confirm(`Delete “${t.name}”?`))return;const r=await fetch(`/api/templates?id=${encodeURIComponent(t.id)}`,{method:'DELETE'}),d=await r.json();if(!r.ok){setError(d.error||'Could not delete template');return}setTemplates(v=>v.filter(x=>x.id!==t.id));if(editingId===t.id)cancel()}
 function duplicate(t:any){setEditingId('');setForm({name:`${t.name} copy`,subject:t.subject,body:t.body});window.scrollTo({top:0,behavior:'smooth'})}
 const shown=templates.filter(t=>!query.trim()||[t.name,t.subject,t.body].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())));if(auth==='loading')return <LoadingScreen/>;if(auth==='guest')return <LoginRequired title="Your templates are private" description="Sign in with Google to create, save and reuse message templates."/>;
 return <div><div className="floating-page-head"><div><div className="eyebrow">TEMPLATES</div><h1>Your message library.</h1><p>Build reusable messages once, then personalize them for every recipient.</p></div></div>{error&&<div className="floating-alert">{error}</div>}<div className="templates-shell"><section className="float-panel template-composer"><div className="template-composer-header"><div><div className="template-form-kicker">{editingId?'EDIT TEMPLATE':'NEW TEMPLATE'}</div><h2>{editingId?'Update your message':'Create a reusable message'}</h2><p>Keep frequently used outreach, invoices, updates and follow-ups ready to send.</p></div><span className="template-status">{templates.length} saved</span></div><div className="template-input-wrap"><label>Name</label><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="template-input-wrap"><label>Subject</label><input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></div><div className="template-input-wrap"><label>Message <span>Dynamic fields supported</span></label><textarea value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></div><div className="template-token-row"><button type="button" className="template-token" onClick={()=>setForm(v=>({...v,body:v.body+'{{name}}'}))}>{'{{name}}'}</button><button type="button" className="template-token" onClick={()=>setForm(v=>({...v,body:v.body+'{{email}}'}))}>{'{{email}}'}</button></div><div className="template-editor-actions"><button className="btn btn-primary template-save-wide" onClick={save} disabled={saving}>{saving?'Saving...':editingId?'Save changes':'Save template'}</button>{editingId&&<button className="ghost-btn" onClick={cancel}>Cancel</button>}</div></section><section className="template-library"><div className="template-filter-bar"><label className="search-wrap"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search templates..."/></label><span>{shown.length} shown</span></div>{loading?<div className="float-panel template-library-empty">Loading templates...</div>:shown.length?shown.map(t=><article className="float-panel template-library-card" key={t.id}><div className="template-card-head"><span className="source-pill">SAVED</span><div className="template-card-actions"><button className="ghost-btn" title="Edit template" onClick={()=>edit(t)}><Pencil size={15}/></button><button className="ghost-btn" title="Duplicate template" onClick={()=>duplicate(t)}><Copy size={15}/></button><button className="ghost-btn danger-text" title="Delete template" onClick={()=>void remove(t)}><Trash2 size={15}/></button></div></div><h3>{t.name}</h3><p>{t.subject}</p><p className="template-body">{t.body}</p></article>):<div className="float-panel template-library-empty"><h3>Your library is empty</h3><p>Save your first reusable message and it will appear here.</p></div>}</section></div></div>
}
